"""Add learning_progress table for intelligent learning module

Revision ID: f11568e3f634
Revises: 36513ab46785
Create Date: 2025-10-09 13:19:06.797212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f11568e3f634'
down_revision: Union[str, Sequence[str], None] = '36513ab46785'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('mastery_level', sa.Integer(), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('next_review_at', sa.DateTime(), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('ease_factor', sa.Float(), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['knowledge_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_progress_entry_id'), 'learning_progress', ['entry_id'], unique=False)
    op.create_index(op.f('ix_learning_progress_id'), 'learning_progress', ['id'], unique=False)
    op.create_index(op.f('ix_learning_progress_next_review_at'), 'learning_progress', ['next_review_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_learning_progress_next_review_at'), table_name='learning_progress')
    op.drop_index(op.f('ix_learning_progress_id'), table_name='learning_progress')
    op.drop_index(op.f('ix_learning_progress_entry_id'), table_name='learning_progress')
    op.drop_table('learning_progress')
    # ### end Alembic commands ###
