"""Initial schema based on final models

Revision ID: f7ccdf1f3b54
Revises: 
Create Date: 2025-10-11 18:04:20.857212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7ccdf1f3b54'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entry_aliases', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('entry_aliases', 'alias_text',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('entry_aliases', 'entry_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_entry_aliases_alias_text'), 'entry_aliases', ['alias_text'], unique=True)
    op.create_index(op.f('ix_entry_aliases_id'), 'entry_aliases', ['id'], unique=False)
    op.create_foreign_key(None, 'entry_aliases', 'knowledge_entries', ['entry_id'], ['id'])
    op.alter_column('follow_ups', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('follow_ups', 'entry_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('follow_ups', 'question',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('follow_ups', 'answer',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('follow_ups', 'timestamp',
               existing_type=sa.NUMERIC(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_index(op.f('ix_follow_ups_id'), 'follow_ups', ['id'], unique=False)
    op.create_foreign_key(None, 'follow_ups', 'knowledge_entries', ['entry_id'], ['id'])
    op.alter_column('knowledge_entries', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('knowledge_entries', 'query_text',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('knowledge_entries', 'entry_type',
               existing_type=sa.TEXT(length=50),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('knowledge_entries', 'analysis_markdown',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('knowledge_entries', 'timestamp',
               existing_type=sa.NUMERIC(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_index(op.f('ix_knowledge_entries_id'), 'knowledge_entries', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_entries_query_text'), 'knowledge_entries', ['query_text'], unique=True)
    op.alter_column('learning_progress', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('learning_progress', 'entry_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('learning_progress', 'mastery_level',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('learning_progress', 'review_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('learning_progress', 'next_review_at',
               existing_type=sa.NUMERIC(),
               type_=sa.Date(),
               nullable=False)
    op.alter_column('learning_progress', 'last_reviewed_at',
               existing_type=sa.NUMERIC(),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('learning_progress', 'ease_factor',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               nullable=False)
    op.alter_column('learning_progress', 'interval',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_learning_progress_entry_id'), 'learning_progress', ['entry_id'], unique=False)
    op.create_index(op.f('ix_learning_progress_id'), 'learning_progress', ['id'], unique=False)
    op.create_index(op.f('ix_learning_progress_next_review_at'), 'learning_progress', ['next_review_at'], unique=False)
    op.create_foreign_key(None, 'learning_progress', 'knowledge_entries', ['entry_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'learning_progress', type_='foreignkey')
    op.drop_index(op.f('ix_learning_progress_next_review_at'), table_name='learning_progress')
    op.drop_index(op.f('ix_learning_progress_id'), table_name='learning_progress')
    op.drop_index(op.f('ix_learning_progress_entry_id'), table_name='learning_progress')
    op.alter_column('learning_progress', 'interval',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('learning_progress', 'ease_factor',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True)
    op.alter_column('learning_progress', 'last_reviewed_at',
               existing_type=sa.Date(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('learning_progress', 'next_review_at',
               existing_type=sa.Date(),
               type_=sa.NUMERIC(),
               nullable=True)
    op.alter_column('learning_progress', 'review_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('learning_progress', 'mastery_level',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('learning_progress', 'entry_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('learning_progress', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_index(op.f('ix_knowledge_entries_query_text'), table_name='knowledge_entries')
    op.drop_index(op.f('ix_knowledge_entries_id'), table_name='knowledge_entries')
    op.alter_column('knowledge_entries', 'timestamp',
               existing_type=sa.DateTime(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('knowledge_entries', 'analysis_markdown',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('knowledge_entries', 'entry_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(length=50),
               nullable=True)
    op.alter_column('knowledge_entries', 'query_text',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('knowledge_entries', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint(None, 'follow_ups', type_='foreignkey')
    op.drop_index(op.f('ix_follow_ups_id'), table_name='follow_ups')
    op.alter_column('follow_ups', 'timestamp',
               existing_type=sa.DateTime(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('follow_ups', 'answer',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('follow_ups', 'question',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('follow_ups', 'entry_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('follow_ups', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint(None, 'entry_aliases', type_='foreignkey')
    op.drop_index(op.f('ix_entry_aliases_id'), table_name='entry_aliases')
    op.drop_index(op.f('ix_entry_aliases_alias_text'), table_name='entry_aliases')
    op.alter_column('entry_aliases', 'entry_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('entry_aliases', 'alias_text',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('entry_aliases', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    # ### end Alembic commands ###
